<a href="https://colab.research.google.com/github/BodaBindhusha/BHARAT-INTERN-TASK-2/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
from __future__ import print_function
import tensorflow as tf
print("TF imported with eager execution!")
print("TF already imported with eager execution!")
evens = tf.constant([2, 4, 6, 10, 12], dtype=tf.int32)
print("evens:", evens)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_even=tf.add(evens,ones)
print("just_beyond_even:", just_beyond_even)
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
evens_doubled = evens * twos
print("evens_doubled:", evens_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())


TF imported with eager execution!
TF already imported with eager execution!
evens: tf.Tensor([ 2  4  6 10 12], shape=(5,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)


InvalidArgumentError: ignored

In [7]:
import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
print("primes:", primes)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_primes = tf.add(primes, ones)
print("just_beyond_primes:", just_beyond_primes)
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
primes_doubled = primes * twos
print("primes_doubled:", primes_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
primes: tf.Tensor([ 2  3  5  7 11 13], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_primes: tf.Tensor([ 3  4  6  8 12 14], shape=(6,), dtype=int32)
primes_doubled: tf.Tensor([ 4  6 10 14 22 26], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

value of some_matrix is:
 [[1 2 3]
 [4 5 6]]


In [9]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# Load and preprocess the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train, 10), to_categorical(y_test, 10)
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2)
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_accuracy:.4f}")

11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/5
1500/1500 [==============================] - 9s 5ms/step - loss: 0.2763 - accuracy: 0.9190 - val_loss: 0.1396 - val_accuracy: 0.9598
Epoch 2/5
1500/1500 [==============================] - 8s 5ms/step - loss: 0.1132 - accuracy: 0.9668 - val_loss: 0.1161 - val_accuracy: 0.9646
Epoch 3/5
1500/1500 [==============================] - 8s 6ms/step - loss: 0.0790 - accuracy: 0.9755 - val_loss: 0.1074 - val_accuracy: 0.9677
Epoch 4/5
1500/1500 [==============================] - 10s 7ms/step - loss: 0.0549 - accuracy: 0.9822 - val_loss: 0.0890 - val_accuracy: 0.9743
Epoch 5/5
313/313 [==============================] - 1s 3ms/step - loss: 0.0898 - accuracy: 0.9731
Test accuracy: 0.9731


In [19]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
np.random.seed(42)
X = np.random.rand(1000, 2)
y = (X[:, 0] + X[:, 1] > 1).astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = Sequential([Input(shape=(2)),Dense(64, activation='relu'),Dense(1, activation='sigmoid')])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)
y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
test_accuracy = accuracy_score(y_test, y_pred_binary)
print(f"Test accuracy: {test_accuracy:.4f}")

Epoch 1/10
20/20 [==============================] - 1s 15ms/step - loss: 0.7133 - accuracy: 0.4625 - val_loss: 0.7016 - val_accuracy: 0.3500
Epoch 2/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6906 - accuracy: 0.5391 - val_loss: 0.6771 - val_accuracy: 0.6250
Epoch 3/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6734 - accuracy: 0.6391 - val_loss: 0.6561 - val_accuracy: 0.6875
Epoch 4/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6568 - accuracy: 0.6734 - val_loss: 0.6376 - val_accuracy: 0.7063
Epoch 5/10
20/20 [==============================] - 0s 6ms/step - loss: 0.6403 - accuracy: 0.7203 - val_loss: 0.6206 - val_accuracy: 0.7250
Epoch 6/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6226 - accuracy: 0.7547 - val_loss: 0.6011 - val_accuracy: 0.7625
Epoch 7/10
20/20 [==============================] - 0s 5ms/step - loss: 0.6026 - accuracy: 0.7906 - val_loss: 0.5817 - val_accuracy: 0.8250
Epoch 8/10
20/20 [=

In [23]:
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
def get_mae(max_leaf_nodes,train_X,val_X, train_y, val_y):
  model=DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes,random_state=0)
  model.fit(train_X,train_y)
  preds_val=model.predict(val_X)
  mae = mean_absolute_error(val_y,preds_val)
  return (mae )
melbourne_data=pd.read_csv('melb_data.csv')
filtered_melbourne_data=melbourne_data.dropna(axis=0)
y= filtered_melbourne_data.Price
melbourne_features = ['Rooms', 'Bathroom', 'Landsize' ,'BuildingArea' ,'YearBuilt' ,'Lattitude', 'Longtitude']
X= filtered_melbourne_data[melbourne_features]
train_X, val_X, train_y, val_y=train_test_split(X, y, random_state=0)
for max_leaf_nodes in [5, 50, 500, 5000]:
  my_mae=get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
  print("Max leaf nodes: %d  \t\t Mean Absolute Error: %d" %(max_leaf_nodes,my_mae) )

FileNotFoundError: ignored